### ISSUE TITLE
Use a custom field as a filtering for embed power BI eport

### ISSUE THREAD

**Issue by louisefagerstrom** [DynamicsNinja/PowerBiEmbedder#11]
Hey!

I have a question about if I can use a custom field to filter a embeded Power BI report. 

Who do I do a filtering on my report?
I have a report in Power BI with customer and the customer in Power BI have some customer ID in CRM and Power BI. 
Can I do a filtering on the report based on the customer ID in CRM and customer ID in Power BI? 

---
- Deployment: Online
- DB Version: 9.1.0.21949
- XTB Version: 1.2020.2.37
- Tool Version: 1.2020.4.2

**Comment by DynamicsNinja** [comment]
Sure, you can do it. You just need to click on the filtering checkbox and select the field from CRM and columun from Power BI report and you will be good to go.

**Comment by rappen** [comment]
As I watched over Louise's virtual shoulder when she tried it yesterday - the dropdown with CDS fields was empty, although the Account entity and a proper form etc was selected.
Ideas?

**Comment by DynamicsNinja** [comment]
CDS field dropdown is populated when you select Entity from the first dropdown so I'm not sure why there are no values at all. We can do a Teams call to see what is happening there if you want.

**Comment by louisefagerstrom** [comment]
Thanks for the help but I restarted the tool and proved again and now I got the values in the CDS field.
But little feedback on the tool.  It is not easy to change a value after you have selected one.
For example, I cannot change entity after selecting for the first time. You have to do everything in exactly the right order for it to work, otherwise you have to shut down the tool and start over.
That is probably way it didn't work for me before.

**Comment by DynamicsNinja** [comment]
Thanks for the feedback and glad you managed to make it work.
