### ISSUE TITLE
Powerbi app users, workspace users

### ISSUE THREAD

**Issue by benito2313** [DynamicsNinja/PowerBiEmbedder#12]
Hello,

When I try to embed powerbi in dynamics 365 crm on the account entity, the users don’t see it but in powerbi they do see it.

This because the users only have access to the published App environment and not to the workspace.
When I add them to the workspace then they can see the report in dynamics 365 crm.
But we don’t won’t users in the workspace in powerbi, they should only be in the published App.

Could you help me ?

Kind regards,

Benito2313

**Comment by DynamicsNinja** [comment]
I'm afraid that this case will not work because embedded PBI report in model-driven apps relies on the workspace security model, so if the user doesn't have the privilege to view reports in the workspace it will not work.
