### ISSUE TITLE
Doesn´t work on tablet/phone

### ISSUE THREAD

**Issue by acac10** [DynamicsNinja/PowerBiEmbedder#17]
When using the Dynamics 365 application on a phone it doesn´t show the report. It says only Log in, and when trying to click log in nothing happens.

When using the new Dynamics 365 Sales application on a phone or tablet it´s stuck on loading.

Should this work on mobile/tablet?

**Comment by DynamicsNinja** [comment]
I tried to load the report on a few Dynamics/Power Apps apps and I couldn't load the report on any of those apps so I assume it's not supported.
