### ISSUE TITLE
Group.read not available as permission in Azure app registration

### ISSUE THREAD

**Issue by Vinisz** [DynamicsNinja/PowerBiEmbedder#20]
Hi,

When looking into the possible app permissions in Azure, "group.read" is not available as an API permission under PowerBI.
This is not in line with the documentation and because I cannot grant it, the XRMtoolbox tool can also not authorize

**Comment by DynamicsNinja** [comment]
I checked the docs for PBI API and now it stands that you need only **Workspace.Read.All** to be able to fetch groups since there is no **Group.Read** permission anymore.
