### ISSUE TITLE
Request that the 'PBI Config values' are only cleared IF a new ENTITY is changed.

### ISSUE THREAD

**Issue by mscottsewell** [DynamicsNinja/PowerBiEmbedder#6]
[Write your comment/feedback/issue here]
![PowerBI Form embedder](https://user-images.githubusercontent.com/6276300/74787587-285c2480-5275-11ea-845b-bd77f9644d9e.png)

---
- Deployment: Online
- DB Version: 9.1.0.12935
- XTB Version: 1.2020.2.37
- Tool Version: 1.2020.2.3

**Comment by DynamicsNinja** [comment]
Interesting feedback, I'll try to find the solution for this one.
