### ISSUE TITLE
Error when exporting and importing form with embedded Power BI

### ISSUE THREAD

**Issue by bzalloua** [DynamicsNinja/PowerBiEmbedder#8]
I successfully added my Power BI report to a contact form in Dynamics 365. However, when I exported the solution containing this form and imported into my TEST instance I got the following error during import against the form component:

"Property GrandChildEntityView isn't declared on the control manifest"

---
- Deployment: Online
- DB Version: 9.1.0.13834
- XTB Version: 1.2020.2.37
- Tool Version: 1.2020.2.7

**Comment by DynamicsNinja** [comment]
Can you send me exported solution ZIP or just customizations.xml file so I can check that everything is generated in the way it should be?

**Comment by DynamicsNinja** [comment]
I’m closing this issue because it has been inactive for a few months. Feel free to reopen it if you are still facing the issue on your side.
