### ISSUE TITLE
Include Report Section with Report ID

### ISSUE THREAD

**Issue by donalmc** [DynamicsNinja/PowerBiEmbedder#9]
Hi

If I add a report page ID to the Report ID I get a GIUD error.
I think just adding something like &ReportSectionec10c779d3e742777e78 to the Report ID would allow us to specify the report page to open on (this works when you manually embed the report).

Is there a way to do this with the your great tool currently?

Thanks,
Donal

**Comment by DynamicsNinja** [comment]
I never played with report pages before, but I'll try to find out if this is possible to include this feature inside the tool. Thanks for the feedback!

**Comment by donalmc** [comment]
Sorry - meant to reply with code that worked when using FormXML Editor

 <TileUrl>https://app.powerbi.com/reportEmbed?reportId=59339c08-9839-496f-aa58-a4a9fe79bd13&amp;pageName=ReportSectionec10c779d3e742777e78</TileUrl>

**Comment by DynamicsNinja** [comment]
No problem, I checked the syntax on the Power BI API page and implemented it that way.
